version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    ports:
    - "2379:2379"
    - "2380:2380"
    command: ["/usr/local/bin/etcd", "--name", "node1",
      "--initial-advertise-peer-urls", "http://etcd:2380", "--listen-peer-urls", "http://0.0.0.0:2380",
      "--advertise-client-urls", "http://etcd:2379", "--listen-client-urls", "http://0.0.0.0:2379",
      "--initial-cluster", "node1=http://etcd:2380",
      "--initial-cluster-state", "new", "--initial-cluster-token", "etcd-cluster"
    ]
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:1.0.1"
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.65
      KAFKA_ADVERTISED_PORT: 9092


      # volumes:
      # - ${PWD}/docker/config:/app/config

